import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Apps } from '@/components/Apps'
import { twMerge } from 'tailwind-merge'
import BrowserHeader from "@/components/BrowserHeader"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Primal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={twMerge(  inter.className, 'h-screen')}>
        <BrowserHeader />
        {/* <Header className="bg-black text-white">asd</Header> */}
        {/* <Apps>asd</Apps> */}
        {children}
      </body>
    </html>
  )
}
